brew install --cask "visual-studio-code"
brew install --cask alfred 
# brew install --cask karabiner-elements
brew install --cask firefox
brew install --cask gimp
brew install --cask menumeters
brew install --cask hammerspoon
brew install --cask mission-control-plus
brew install --cask swish
brew install --cask autumn
brew install --cask loom
brew install --cask sip
# brew install --cask contexts
# brew install --cask witch
brew install --cask microsoft-teams
brew install --cask middle
brew install --cask alt-tab
brew install --cask local
brew install --cask sublime-text
brew install --cask dbeaver-community

git clone https://github.com/sdeli/hammerspoon.git "$HOME/.hammerspoon"

defaults write com.apple.Finder AppleShowAllFiles true
killall Finder
defaults write com.apple.finder QuitMenuItem -bool YES && killall Finder
defaults write com.apple.dock autohide-delay -float 0; killall Dock
defaults write com.apple.dock autohide-time-modifier -float 0.1; killall Dock

curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/darwin/amd64/kubectl"
curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/darwin/amd64/kubectl.sha256"
echo "$(cat kubectl.sha256)  kubectl" | shasum -a 256 --check
chmod +x ./kubectl
mv ./kubectl /usr/local/bin/kubectl
 chown root: /usr/local/bin/kubectl

brew install zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"